# Basic settings
from_latest_tag = true
ignore_merge_commits = true

[commit_types]
app = { changelog_title = "Reference App" }

# Changelog settings
[changelog]
path = "CHANGELOG.md"
template = "config/cocogitto/templates/remote_extended"
remote = "github.com"
owner = "rdkcentral"
repository = "BartonCore"
