#!/usr/bin/env bash
# ------------------------------ tabstop = 4 ----------------------------------
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2024 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# ------------------------------ tabstop = 4 ----------------------------------

notice() {
    echo "-- $0: $@"
}

set -e

if [ -f /.dockerenv ]; then
    echo "ERROR: dockerw is already running inside a container."
    echo "Run commands directly in the current container instead of nesting containers."
    exit 1
fi

COMPOSE_INTERACTIVE_FLAGS=""
EXTRA_ENV="-e SSH_AUTH_SOCK"
DEV_VOL=""
HOST_NETWORK=""

while getopts ":ne:dH" opt; do
    case ${opt} in
    n) # process option n
        COMPOSE_INTERACTIVE_FLAGS="--no-TTY"
        ;;
    e) # extra environment variables
        EXTRA_ENV="${EXTRA_ENV} -e ${OPTARG}"
        ;;
    d) # add /dev volume mapping
        DEV_VOL="-v /dev:/dev"
        ;;
    H) # use host networking (useful for Matter device access)
        HOST_NETWORK="1"
        ;;
    esac
done
shift "$(($OPTIND - 1))"

DIR=$(pwd)

# generate the `docker/.env` file and ensure the network/image is created
$DIR/docker/setupDockerEnv.sh

# `docker compose run` has no `--network` flag, so host networking is applied by
# layering the host-network override compose file (which sets network_mode: host
# and resets the base network) rather than passing a flag to the run command.
COMPOSE_FILES="-f ${DIR}/docker/compose.yaml"

if [ -n "$HOST_NETWORK" ]; then
    COMPOSE_FILES="${COMPOSE_FILES} -f ${DIR}/docker/compose.host-network.yaml"
fi

EXTRA_VOLUMES="${DEV_VOL}"

VOLUMES_ARGS="-v $HOME:$HOME
             $EXTRA_VOLUMES"

# create a unique container name prefixed with the user id, useful when on a shared machine
USER_ID=$(id -u -n)
RANDOM_NUMBER=$(shuf -i 100000-999999 -n 1)
CONTAINER_NAME="${USER_ID}_${RANDOM_NUMBER}"

docker compose ${COMPOSE_FILES} run \
    --rm \
    --name ${CONTAINER_NAME} \
    ${COMPOSE_INTERACTIVE_FLAGS} \
    --workdir "${DIR}" \
    ${VOLUMES_ARGS} \
    ${EXTRA_ENV} \
    barton \
    $*
