#!/bin/bash
# ------------------------------ tabstop = 4 ----------------------------------
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# ------------------------------ tabstop = 4 ----------------------------------

#
# Created by Kevin Funderburg on 1/6/2025.
#

# Entrypoint script executed when container is spun up. This is dependent on the environment
# variables generated by `docker/setupDockerEnv.sh`. As a result, When performing `docker run`,
# you will need to specify the path to the generated .env file from setupDockerEnv.sh.
#
# example: `docker run --env-file $BARTON_TOP/docker/.env barton_builder_$USER`
# see dockerw for another example

# Check if required environment variables are set
if [ -z "$MATTER_SAMPLE_APPS_PATH" ] || [ -z "$BARTON_PYTHONPATH" ] || [ -z "$LIB_BARTON_SHARED_PATH" ]; then
    echo "One or more required environment variables are not set."
    exit 1
fi

# see `docker/setupDockerEnv.sh` for more details on these custom PATHs
# NOTE: do not add a custom PATH here without first defining it in `docker/setupDockerEnv.sh`
export PATH=$MATTER_SAMPLE_APPS_PATH:$PATH
export PYTHONPATH=$PYTHONPATH:$BARTON_PYTHONPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB_BARTON_SHARED_PATH

# Start a shell to keep the container running
exec "$@"
