#------------------------------ tabstop = 4 ----------------------------------
#
# Copyright (C) 2024 Comcast
#
# All rights reserved.
#
# This software is protected by copyright laws of the United States
# and of foreign countries. This material may also be protected by
# patent laws of the United States and of foreign countries.
#
# This software is furnished under a license agreement and/or a
# nondisclosure agreement and may only be used or copied in accordance
# with the terms of those agreements.
#
# The mere transfer of this software does not imply any licenses of trade
# secrets, proprietary technology, copyrights, patents, trademarks, or
# any other form of intellectual property whatsoever.
#
# Comcast retains all ownership rights.
#
#------------------------------ tabstop = 4 ----------------------------------

#
# Created by Kevin Funderburg on 09/20/2024
#

# Setting the name element to the user helps keep the container name easy to identify
# by namespacing it with the user's name. Example: $USER-barton-devcontainer-1
name: $BUILDER_USER-barton

services:
    devcontainer:
        extends:
            file: ../docker/compose.yaml
            service: barton

        build:
            # This compose file's build target will handle the non-root user creation
            # for the devcontainer to login to.
            target: user_builder
            args:
                - BUILDER_USER=$BUILDER_USER
                - BUILDER_GID=$BUILDER_GID
                - BUILDER_UID=$BUILDER_UID

        # Keep the container running indefinitely
        command: sleep infinity
