#!/usr/bin/env python3

# ------------------------------ tabstop = 4 ----------------------------------
#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2026 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# ------------------------------ tabstop = 4 ----------------------------------

"""
Embed a JavaScript file as a C/C++ header with a string constant.

This script reads a JavaScript bundle file and generates a C header that
embeds the entire script as a string constant. This allows the JavaScript
code to be compiled directly into the binary without needing to read it
from the filesystem at runtime.

Usage:
    python3 embed-js-as-header.py --input <js_file> --output <header_file> --variable <name>
"""

import argparse
import os
import sys
import random
import string
import uuid


def escape_for_c_string(content: str) -> tuple[str, str]:
    """
    Escape a string for embedding in a C/C++ raw string literal.

    We use a raw string literal R"DELIMITER(...)DELIMITER" to avoid most escaping,
    but we still need to ensure the delimiter doesn't appear in the content.
    C++ raw string delimiters are limited to 16 characters.
    """
    # Try a short base delimiter first
    base = "JS"
    delimiter = base
    counter = 0
    
    # Increment counter until we find a delimiter not in content or hit length limit
    while delimiter in content and len(delimiter) < 16:
        counter += 1
        delimiter = f"{base}{counter}"
    
    # If we hit the length limit with base "JS", try a random delimiter
    if delimiter in content and len(delimiter) >= 16:
        for _ in range(100):  # Try up to 100 random delimiters
            delimiter = ''.join(random.choices(string.ascii_uppercase + string.digits, k=12))
            if delimiter not in content:
                break
    
    # Final fallback: use a UUID-based delimiter (guaranteed unique)
    if delimiter in content:
        delimiter = str(uuid.uuid4()).replace('-', '')[:16]
    
    return content, delimiter


def generate_header(input_path: str, output_path: str, variable_name: str) -> None:
    """
    Generate a C header file containing the JavaScript content as a string constant.
    """
    # Read the input JavaScript file
    with open(input_path, 'r', encoding='utf-8') as f:
        js_content = f.read()

    # Get file stats for metadata
    file_size = os.path.getsize(input_path)
    input_basename = os.path.basename(input_path)

    # Get safe delimiter for raw string literal (max 16 chars)
    escaped_content, delimiter = escape_for_c_string(js_content)

    # Generate the header guard from the output file name
    output_basename = (
        os.path.basename(output_path).upper().replace(".", "_").replace("-", "_")
    )
    header_guard = f"{output_basename}_"

    header_content = f"""// ------------------------------ tabstop = 4 ----------------------------------
//
// AUTO-GENERATED FILE - DO NOT EDIT
//
// This file was automatically generated by embed-js-as-header.py
// Source: {input_basename}
// Size: {file_size} bytes
//
// If not stated otherwise in this file or this component's LICENSE file the
// following copyright and licenses apply:
//
// Copyright 2026 Comcast Cable Communications Management, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// ------------------------------ tabstop = 4 ----------------------------------

#pragma once

#ifndef {header_guard}
#define {header_guard}

#include <cstddef>

namespace barton
{{

/**
 * Embedded JavaScript bundle.
 *
 * This string contains the bundled JavaScript that will be loaded into
 * the QuickJS runtime for SBMD script execution.
 *
 * Source file: {input_basename}
 */
inline constexpr const char* {variable_name} = R"{delimiter}({escaped_content}){delimiter}";

/**
 * Size of the embedded bundle in bytes (excluding null terminator).
 */
inline constexpr std::size_t {variable_name}Size = {len(js_content.encode('utf-8'))};

}} // namespace barton

#endif // {header_guard}
"""

    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    # Write the header file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"Generated: {output_path}")
    print(f"  Source: {input_path}")
    print(f"  Size: {file_size} bytes")
    print(f"  Variable: {variable_name}")


def main():
    parser = argparse.ArgumentParser(
        description='Embed a JavaScript file as a C/C++ header constant'
    )
    parser.add_argument(
        '--input', '-i',
        required=True,
        help='Input JavaScript file to embed'
    )
    parser.add_argument(
        '--output', '-o',
        required=True,
        help='Output C/C++ header file path'
    )
    parser.add_argument(
        '--variable', '-v',
        default='kMatterJsClustersBundle',
        help='Name of the C variable (default: kMatterJsClustersBundle)'
    )

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    generate_header(args.input, args.output, args.variable)


if __name__ == '__main__':
    main()
